tailor:
  mapping_save_path: /home/jlurobot/桌面/tailor/src/tailor/map
  livox_topic: /livox_hap
  velodyne_topic: /u2102
  degenerate_threshold: 10.0 # 200.0
  livox_transform: [ -1.44776,    -0.0634472,   1.35995,     0.00433622,  0.04771802, -0.00743534 ]
  use_livox: true
  use_velodyne: true
