tailor:
  mapping_save_path: /home/jlurobot/桌面/tailor/src/tailor/map
  livox_topic: /livox_hap
  velodyne_topic: /u2102
  livox_transform: [ -1.44776, -0.0634472,  1.35995, 0.00433622, 0.04771802, -0.00743534 ]
  use_livox: false
  use_velodyne: true
  
  LM:
    method: 0 # 0: LM2, 1: GTSAM
    degenerate_threshold: 10.0 # 200.0
  
  key_frame:
    x: 1.2
    y: 1.2
    z: 1.2
    roll: 0.02
    pitch: 0.02
    yaw: 0.02

  loop:
    enable: true
    max_loss: 0.02
    loop_reset: 2
    initial_load: 100
    
