gen:
  pose: /home/jlurobot/桌面/tailor/src/tailor/map/1698136963.txt
  livox_topic: /livox_hap
  velodyne_topic: /u2102
  livox_transform: [ -1.44776, -0.0634472,  1.35995, 0.00433622, 0.04771802, -0.00743534 ]
  global_map: /home/jlurobot/桌面/tailor/src/tailor/map/global_map2.pcd